[package]
name = "entity_macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
entity_core = { path = "../entity_core" }
syn = { version = "2", features = ["full", "extra-traits"] }
quote = "1"
proc-macro2 = "1"
