[package]
name = "entity_core"
version = "0.1.0"
edition = "2024"

[dependencies]
aws-sdk-dynamodb = "1.93.0"
serde_dynamo = { version = "4.2.14", features = ["aws-sdk-dynamodb+1"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.145"